name: CI Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build Main Branch
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Build Source with Maven
        working-directory: ./name-source
        run: ./mvnw --batch-mode clean package

      - name: Build Processor with Maven
        working-directory: ./name-processor
        run: ./mvnw --batch-mode clean package

      - name: Build Sink with Maven
        working-directory: ./name-sink
        run: ./mvnw --batch-mode clean package
